In [1]:
import torch

In [4]:
a=torch.load("TextCNN.ckpt")

In [8]:
a

OrderedDict([('embedding.weight',
              tensor([[ 0.1617,  0.3023,  0.5889,  ...,  0.3858,  0.5684,  0.0573],
                      [-0.0346, -0.1079,  0.0464,  ..., -0.1607, -0.3050,  0.1516],
                      [-0.0256,  0.0572, -0.2512,  ...,  0.2919, -0.3903, -0.0469],
                      ...,
                      [-0.2030,  0.1445, -0.0035,  ..., -0.2927, -0.1555,  0.0662],
                      [ 0.5052,  0.6515,  0.4099,  ...,  0.6391,  0.2736,  0.7934],
                      [ 0.2890,  0.8864,  0.6253,  ...,  0.6731,  0.7833,  0.1340]],
                     device='cuda:0')),
             ('convs.0.weight',
              tensor([[[[-0.0876, -0.0410,  0.0085,  ...,  0.0478, -0.0010,  0.0868],
                        [-0.0331,  0.0392,  0.0297,  ...,  0.0746, -0.0147, -0.0683]]],
              
              
                      [[[ 0.0128, -0.0447, -0.0368,  ...,  0.0687,  0.0041,  0.0474],
                        [ 0.0131, -0.0339, -0.0131,  ..., -0.0066, -0.00

In [9]:
b=torch.load("best.pt")
b

{'epoch': 4,
 'model_state_dict': OrderedDict([('embedding_layer.embedding.weight',
               tensor([[-0.0047, -0.3210, -1.2942,  ..., -0.2643,  1.0605, -1.1085],
                       [ 1.4122, -1.1482, -0.3718,  ...,  1.4765,  0.1181, -0.0996],
                       [ 0.1696,  1.6891, -1.7404,  ...,  1.5773, -0.0574,  0.5021],
                       ...,
                       [ 1.0484,  0.1276,  1.9397,  ..., -0.2986, -0.4340, -0.4957],
                       [ 1.2387,  2.4273, -1.3080,  ...,  0.6407, -0.5107, -1.7617],
                       [-1.8834, -0.8009, -0.1613,  ...,  0.5234,  1.1071,  0.5687]],
                      device='cuda:0')),
              ('classifier.rnn.rnn.weight_ih_l0',
               tensor([[ 0.0048, -0.0045,  0.0493,  ..., -0.0302,  0.0115, -0.0441],
                       [-0.0377,  0.0974, -0.0330,  ...,  0.0447, -0.0223,  0.0844],
                       [-0.0061,  0.0453, -0.0762,  ...,  0.0652, -0.0029,  0.0191],
                       ...,
   